### Possible Issues

`calories_day` can be named better

`comfort_food` is not yet coded

`father_profession`, `mother_profession` not coded

`food_childhood` not coded 

`healthy_feel`, `life_rewarding` interesting scale: 1 for strongest, 10 for weakest 

`healthy_meal` not coded 

`meals_dinner_friend` not coded 

`type_sports` not coded 

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('food_coded.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   GPA                           123 non-null    object 
 1   Gender                        125 non-null    int64  
 2   breakfast                     125 non-null    int64  
 3   calories_chicken              125 non-null    int64  
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64  
 7   comfort_food                  124 non-null    object 
 8   comfort_food_reasons          124 non-null    object 
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64  
 12  cuisine                       108 non-null    float64
 13  diet_

In [4]:
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4       2          1               430           NaN           315.0   
1  3.654       1          1               610           3.0           420.0   
2    3.3       1          1               720           4.0           420.0   
3    3.2       1          1               430           3.0           420.0   
4    3.5       1          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

### Removing redundancies

Because these columns have already been coded, we only keep the codes and remove the uncoded columns.

In [5]:
df.drop(['comfort_food_reasons', 'diet_current', 'eating_changes', 'fav_cuisine', 'ideal_diet'], inplace=True, axis=1)

`comfort_food_reasons_coded` and `comfort_food_reasons_coded.1` are almost the same column, except that the former has `nan` values. Hence, we choose the latter to keep.

In [6]:
df.drop(['comfort_food_reasons_coded'], inplace=True, axis=1)
df.rename({'comfort_food_reasons_coded.1': 'comfort_food_reasons_coded'}, axis=1, inplace=True)

There are two codings for `eating_changes`: `eating_changes_coded` and `eating_changes_coded1`. The latter is more detailed than the forever, so we decide to keep it.

In [7]:
df.drop(['eating_changes_coded'], inplace=True, axis=1)
df.rename({'eating_changes_coded1': 'eating_changes_coded'}, axis=1, inplace=True)

### Missing Values

`GPA` is an `object` column in this dataset. Hence, further data exploration must be made on the column so that its data type can be changed to the more appropriate `float`.

In [8]:
df['GPA'].value_counts()

3.5           13
3             11
3.2           10
3.7           10
3.3            9
3.4            9
3.6            7
3.9            7
3.8            6
2.8            5
4              4
3.1            3
2.9            2
3.83           2
2.6            2
2.4            1
3.79 bitch     1
3.73           1
2.71           1
3.92           1
3.68           1
3.75           1
Unknown        1
3.77           1
3.63           1
3.67           1
3.89           1
Personal       1
3.35           1
3.292          1
3.605          1
3.654          1
3.65           1
3.87           1
2.2            1
3.904          1
2.25           1
3.882          1
Name: GPA, dtype: int64

We should extract the number from `3.79 bitch`, and turn `Unknown` and `Personal` into `NaN` values to be imputed later.

Here, we note that `Personal ` has a space after the word. This is important in accessing it.

In [9]:
df['GPA'].replace({
    '3.79 bitch': 3.79,
    'Unknown': np.NaN,
    'Personal ': np.NaN
}, inplace=True)

In [10]:
df['GPA'].value_counts()

3.5      13
3        11
3.7      10
3.2      10
3.3       9
3.4       9
3.6       7
3.9       7
3.8       6
2.8       5
4         4
3.1       3
2.9       2
2.6       2
3.83      2
3.79      1
2.71      1
3.73      1
2.4       1
3.92      1
3.68      1
3.75      1
3.77      1
3.63      1
3.67      1
3.65      1
3.35      1
3.292     1
3.605     1
3.89      1
3.654     1
3.87      1
2.2       1
3.904     1
2.25      1
3.882     1
Name: GPA, dtype: int64

In [11]:
df['GPA'] = pd.to_numeric(df['GPA'])

The `weight` column is also an `object` column, instead of `int` or `float`. Hence, we have to do more data exploration.

In [12]:
df['weight'].value_counts()

135                         8
140                         8
150                         7
170                         7
175                         6
180                         6
155                         6
185                         6
165                         5
190                         5
125                         5
145                         4
200                         4
130                         4
120                         3
160                         3
129                         2
113                         2
128                         2
167                         2
210                         2
118                         1
192                         1
187                         1
112                         1
144 lbs                     1
127                         1
260                         1
184                         1
230                         1
138                         1
265                         1
205                         1
169       

We can extract the numbers from `144 lbs` and `Not sure, 240`, while `I'm not answering this.` can be changed to `NaN`.

Here, we also note that `I'm not answering this. ` also has a space after the period.

In [13]:
df['weight'].replace({
    '144 lbs': 144,
    'Not sure, 240': 240,
    'I\'m not answering this. ': np.NaN
}, inplace=True)

In [14]:
df['weight'].value_counts()

135    8
140    8
150    7
170    7
155    6
175    6
180    6
185    6
165    5
125    5
190    5
145    4
200    4
130    4
160    3
120    3
210    2
113    2
167    2
128    2
129    2
144    1
112    1
127    1
260    1
184    1
230    1
118    1
138    1
192    1
265    1
187    1
169    1
168    1
100    1
205    1
115    1
105    1
195    1
123    1
264    1
110    1
116    1
137    1
240    1
156    1
Name: weight, dtype: int64

In [15]:
df['weight'] = pd.to_numeric(df['weight'])

Next, we split the columns with missing data into categorical and numerical variables.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 54 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   GPA                         121 non-null    float64
 1   Gender                      125 non-null    int64  
 2   breakfast                   125 non-null    int64  
 3   calories_chicken            125 non-null    int64  
 4   calories_day                106 non-null    float64
 5   calories_scone              124 non-null    float64
 6   coffee                      125 non-null    int64  
 7   comfort_food                124 non-null    object 
 8   cook                        122 non-null    float64
 9   comfort_food_reasons_coded  125 non-null    int64  
 10  cuisine                     108 non-null    float64
 11  diet_current_coded          125 non-null    int64  
 12  drink                       123 non-null    float64
 13  eating_changes_coded        125 non

In [17]:
cat = [
    'calories_day',
    'calories_scone',
    'cook',
    'cuisine',
    'drink',
    'employment',
    'exercise',
    'father_education',
    'fav_food',
    'income',
    'life_rewarding',
    'marital_status',
    'mother_education',
    'on_off_campus',
    'persian_food',
    'self_perception_weight',
    'soup',
    'sports',
    'tortilla_calories',
]

num = [
    'GPA',
    'weight'
]

All categorical columns are actually `int` or `cat` columns in the dataset, but it was observed that this was due to the coding used in the original dataset, where numbers are assigned to text data. We then impute using the function defined below:

In [18]:
def impute_na(col_name, col_type):
    '''
    This function is used to avoid retyping too much
    '''
    if col_type == 'cat':
        df[col_name] = df[col_name].fillna(value=df[col_name].mode()[0])
    elif col_type == 'num':
        df[col_name] = df[col_name].fillna(value=df[col_name].mean())
    else:
        print('Nothing happened!')

In [19]:
for col in cat:
    impute_na(col, 'cat')
    
for col in num:
    impute_na(col, 'num')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 54 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   GPA                         125 non-null    float64
 1   Gender                      125 non-null    int64  
 2   breakfast                   125 non-null    int64  
 3   calories_chicken            125 non-null    int64  
 4   calories_day                125 non-null    float64
 5   calories_scone              125 non-null    float64
 6   coffee                      125 non-null    int64  
 7   comfort_food                124 non-null    object 
 8   cook                        125 non-null    float64
 9   comfort_food_reasons_coded  125 non-null    int64  
 10  cuisine                     125 non-null    float64
 11  diet_current_coded          125 non-null    int64  
 12  drink                       125 non-null    float64
 13  eating_changes_coded        125 non

The remaining columns with `NaN`s are the answers to open-ended questions.